test

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -101,10 +101,22 @@ jobs:
             docker-compose build
             docker-compose up -d --force-recreate
 
-            docker -compose ps
-            # Проверяем логи контейнера web
-            docker logs safeisol-prod-web-1
+            docker ps --format "{{.Names}}"
+            
+            # Ждем, пока контейнер web будет готов выполнять команды
+            max_attempts=20
+            attempt=0
+            until docker-compose exec web python manage.py check > /dev/null 2>&1 || [ $attempt -eq $max_attempts ]; do
+              echo "Waiting for web container to be ready... ($attempt/$max_attempts)"
+              attempt=$((attempt + 1))
+              sleep 3
+            done
 
-            # Выполняем миграции, сбор статики и загрузку данных внутри контейнера
+            if [ $attempt -eq $max_attempts ]; then
+              echo "Web container failed to start in time."
+              exit 1
+            fi
+
+            # Выполняем миграции и загрузку данных внутри контейнера
             docker-compose exec web python manage.py migrate --noinput
             docker-compose exec web python manage.py loaddata data.json
